# filter method accepts a function and an iterable
# returns those elements that returned True when supplied to the function
myList = [20, 35, 56, 82, 55, 90]
even = list(filter(lambda num: (num%2) == 0, myList))
print(even)

# map method accepts a function and an iterable
# a new list is produced with elements generated by the given function for every item
myList = [2, 3, 5, 8, 6, 9]
Square = list(map(lambda num: num**2, myList))
print(Square)

# lambda with if - else
Greater = lambda x, y: x if(x > y) else y
print(Greater(3,9))