import calendar
import time
import datetime as dt
import calendar as cl

# To get the current time
# here time() returns number of ticks since 12 AM, 1st January 1970
# Following code returns a tuple
print(time.localtime(time.time()))

# Formatting the current time
print("Formatted time: ", time.asctime(time.localtime(time.time())))

# halt the execution for given time
for i in range(5):
    print(i)
    time.sleep(1)  # Each number will be generated by 1s pause

# print current datetime
print("Current datetime is : ", dt.datetime.now() )

# creating datetime object for the passed date
print(dt.datetime(2022, 8, 12))

print("***********Comparison of dates < > <= >=********")

# printing the calendar for specific month by passing year and month
print(calendar.month(1999,2))

# printing the calendar for specific year
print(calendar.prcal(2022))